name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
    - name: Setup node 20.x
      uses: actions/setup-node@v3
      with:
          node-version: 20.x
    - name: Build
      run: npm i
    - name: Lint
      run: npm run lint
    - name: Package
      run: npx vsce package -o tarantool-vscode.vsix
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Tarantool VSCode
        path: ${{ github.workspace }}/tarantool-vscode.vsix
